apiVersion: v1
kind: Service
metadata:
  name: chatapp-user-service
spec:
  type: LoadBalancer
  selector:
    app: chatapp-user-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082git