server:
  port: 8082

spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:mysql://34.68.129.10:3306/chatapp_user?allowPublicKeyRetrieval=true&useSSL=false
    username: chatapp-user-mysql
    password: "&14EM'^9SDMh1kx|"
    driver-class-name: com.mysql.cj.jdbc.Driver