server:
  port: 8082

spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/chatapp_user
    username: root
    password: "root"
    driver-class-name: com.mysql.cj.jdbc.Driver

# config server is only used when running in docker
  config:
    import: optional:configserver:http://localhost:8888