server:
  port: 8082

spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/chatapp_user
    username: root
    password: "root"
    driver-class-name: com.mysql.cj.jdbc.Driver

  application:
      name: nooooo
  profiles:
    active: test
  config:
    import: optional:configserver:http://localhost:8881